### ISSUE TITLE
Target available and target assigned values are different in platerun vs summing fields

### ISSUE THREAD

**Issue by deleenm** [jcbird/ppv#10]
Hi @jcbird, I ran into a strange issue today. This issue is true both with the number of targets available and the number of targets assigned. It seems that the number of targets varies depending on whether I do the whole run, or I sum up the targets field by field in the run, which doesn't make sense. Here is a short piece of code that demonstrates the issue:
```python
from astropy.table import Table
import numpy as np
import ppv

planet_targetDB = Table.read('targets/mwm_planet_0.1.0_targetdb.fits.gz')
from ppv.targets import Targets
planet_targets = Targets(planet_targetDB)
from ppv.groups import Platerun
run = Platerun('2020.10.a.mwm-bhm')
print("Tot from Platerun: {}".format(np.sum(planet_targets.available_in(run))))
tot_avail = 0
for field in run.fields:
    num_avail = np.sum(planet_targets.available_in(field))
    tot_avail = tot_avail + num_avail
print("Tot from Fields: {}".format(tot_avail))
```

The output is:
Tot from Platerun: 1459
Tot from Fields: 1549

Any thoughts as to what is going on, the numbers are close, but not that close,

Nathan

**Comment by jcbird** [comment]
Yep, this makes sense. It is due to field overlap!

When doing the available in a platerun, if an object is available in more
than one field, it will still only count twice. The boolean mask returned
by "available_in" is answering T/F to whether or not a particular object is
available AT LEAST ONCE.
When you go field by field, if an object can be observed in two fields due
to overlap, then it is counted twice.
Let me know if that doesn't make sense or if you still think there is an
extra discrepancy.


--------------------------------------------------------------------------------
Jonathan Bird (he/him/his)
Research Assistant Professor
Department of Physics and Astronomy, Vanderbilt University
