### ISSUE TITLE
No Utah account (yet)

### ISSUE THREAD

**Issue by BGaensicke** [jcbird/ppv#7]
I sent the request for an account to Joel last Thursday, he forwarded it immediately, but I guess it will take a bit of time to get it approved & set up.

**Comment by jcbird** [comment]
Hmm, that is too long! If you are still up, let me know if you hear anything before going to bed. If not, I can simply send you a tarball separately and we can go from there until it's fixed. Likewise for anyone else with this issue.

**Comment by BGaensicke** [comment]
I got an e-mail from Joel an hour ago, the account creation has been initiated, but there are a few steps that still need to trickle through - so, yes, if for this time only, you could put a tarball somewhere? The good news is, I got ppv installed - well, at least it starts up and asks for my Utah password ;)

**Comment by jcbird** [comment]
Ok, I will send you a tarball. Extract and unzip it. The root directory of the tarball will be called 'sdss5platefiles'. You can move this directory to wherever you wish and you can rename it whatever you wish. Do NOT change any of the subdirectories or their contents. 

In you ppv_setup.ini, point your `plate_dir` to the newly extracted directory and use NONE as your sdss_org:

> sdss_org = NONE

Enter exactly as above, including allcaps. This will bypass checking Utah for the time being. I am not going to put this in the README because it will fail unless you have all the relevant plate files, which I am going to email you as the tarball. Cheers.
Let me know if this works so I can close the issue when you get a chance. Thanks!

**Comment by BGaensicke** [comment]
Thanks Jon, works fine so far... now exploring the magic of ppv.

**Comment by jcbird** [comment]
Great and thanks for all your feedback!
